os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan profile new default --detect
  - conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
  - conan profile update settings.compiler.cppstd=14 default
  - conan profile update settings.compiler.libcxx=libstdc++11 default
script:
# Download dependencies and build project
  - conan export . paraview/5.5.2@CHM/dev
  - conan install . --build missing


